In [26]:
import pandas as pd
import requests

In [27]:
def page_gares(numero_page) :
    return requests.get(
        ('https://api.sncf.com/v1/coverage/sncf/stop_areas?start_page={}').format(numero_page),
        auth=("5b3cc55f-1fec-4bd9-8e09-957b4de0c84b", ''))

page_initiale = page_gares(0)
item_per_page = page_initiale.json()['pagination']['items_per_page']
total_items = page_initiale.json()['pagination']['total_result']
dfs = []
print_done = {}

for page in range(int(total_items/item_per_page)+1) :
    stations_page = page_gares(page)

    ensemble_stations = stations_page.json()

    if 'stop_areas' not in ensemble_stations:
        # pas d'arrêt
        continue

    # on ne retient que les informations qui nous intéressent
    for station in ensemble_stations['stop_areas']:

        station['lat'] = station['coord']['lat']
        station["lon"]  = station['coord']['lon']

        if 'administrative_regions' in station.keys() :
            for var_api, var_df in zip(['insee','name','label','id','zip_code'],
                                       ['insee','region','label_region','id_region','zip_code']):
                try:
                    station[var_df] = station['administrative_regions'][0][var_api]
                except KeyError:
                    if var_api not in print_done:
                        print("key '{0}' not here but {1}".format(var_api,
                                ",".join(station['administrative_regions'][0].keys())))
                        print_done[var_api] = var_api

        [station.pop(k,None) for k in ['coord','links','administrative_regions', 'type', 'codes']]

    stations = ensemble_stations['stop_areas']
    try:
        dp = pd.DataFrame(stations)
    except Exception as e:
        raise Exception("Problème de données\n{0}".format(stations)) from e

    dfs.append(dp)

import pandas
df = pandas.concat(dfs)
df.to_csv("./ensemble_gares.csv")
print(df.shape)
df.head()

(4999, 11)

,name,label,timezone,id,lat,lon,insee,region,label_region,id_region,zip_code
0,,,Europe/Paris,stop_area:SNCF:87713743,0,0,NaN,NaN,NaN,NaN,NaN
1,Abancourt,Abancourt (Abancourt),Europe/Paris,stop_area:SNCF:87313759,49.685621,1.774297,60001,Abancourt,Abancourt (60220),admin:fr:60001,60220
2,Abbaretz,Abbaretz (Abbaretz),Europe/Paris,stop_area:SNCF:87481614,47.555241,-1.524289,44001,Abbaretz,Abbaretz (44170),admin:fr:44001,44170
3,Abbeville,Abbeville (Abbeville),Europe/Paris,stop_area:SNCF:87317362,50.102175,1.824538,80001,Abbeville,Abbeville (80100),admin:fr:80001,80100
4,Ablon,Ablon (Ablon-sur-Seine),Europe/Paris,stop_area:SNCF:87545269,48.725443,2.419213,94001,Ablon-sur-Seine,Ablon-sur-Seine (94480),admin:fr:94001,94480

In [28]:
dfg=pd.read_json("gares.json")
print(len(dfg))
dfg.head()

159

,Nom_Gare,INSEE_REG,NOM_REG,INSEE_DEP,NOM_DEP,Latitude,Longitude,code_postal,service_wifi,traffic,city
0,Aix-en-Provence TGV,84,Auvergne-Rhône-Alpes,1,Ain,46.097,4.847,13592,Oui,high,Chaneins
1,Bourg-en-Bresse,84,Auvergne-Rhône-Alpes,1,Ain,46.196,5.275,1000,Oui,high,Bourg-en-Bresse
2,Cluses,84,Auvergne-Rhône-Alpes,1,Ain,46.171,5.577,74300,Non,high,Montréal-la-Cluse
3,Nurieux,84,Auvergne-Rhône-Alpes,1,Ain,46.181,5.521,1760,Non,medium,Nurieux-Volognat
4,Antibes,93,Provence-Alpes-Côte d'Azur,6,Alpes-Maritimes,43.584,7.108,6600,Oui,high,Antibes

In [32]:
df2 = dfg.merge(df, left_on='Nom_Gare', right_on='name')
print(len(df2))
df2=df2[["Nom_Gare","INSEE_REG","NOM_REG","INSEE_DEP","NOM_DEP","Latitude","Longitude","code_postal","service_wifi","traffic","city","id_region"]]

131

In [34]:
df2.to_json(r'Data/gares.json',orient="records")

In [33]:
df2

,Nom_Gare,INSEE_REG,NOM_REG,INSEE_DEP,NOM_DEP,Latitude,Longitude,code_postal,service_wifi,traffic,city,id_region
0,Aix-en-Provence TGV,84,Auvergne-Rhône-Alpes,1,Ain,46.097,4.847,13592,Oui,high,Chaneins,admin:fr:13001
1,Bourg-en-Bresse,84,Auvergne-Rhône-Alpes,1,Ain,46.196,5.275,1000,Oui,high,Bourg-en-Bresse,admin:fr:01053
2,Cluses,84,Auvergne-Rhône-Alpes,1,Ain,46.171,5.577,74300,Non,high,Montréal-la-Cluse,admin:fr:74081
3,Antibes,93,Provence-Alpes-Côte d'Azur,6,Alpes-Maritimes,43.584,7.108,6600,Oui,high,Antibes,admin:fr:06004
4,Cannes,93,Provence-Alpes-Côte d'Azur,6,Alpes-Maritimes,43.653,7.146,6400,Oui,high,Cagnes-sur-Mer,admin:fr:06029
...,...,...,...,...,...,...,...,...,...,...,...,...
126,Remiremont,44,Grand Est,88,Vosges,48.006,6.604,88200,Non,high,Remiremont,admin:fr:88383
127,Saint-Dié-des-Vosges,44,Grand Est,88,Vosges,48.293,6.962,88100,Non,high,Saint-Dié-des-Vosges,admin:fr:88413
128,Saint-Michel - Valloire,44,Grand Est,88,Vosges,48.157,6.134,73450,Non,high,Les Vallois,admin:fr:73261
129,Belfort - Montbéliard TGV,27,Bourgogne-Franche-Comté,90,Territoire de Belfort,47.637,6.858,90400,Oui,high,Belfort,admin:fr:90068
130,Massy TGV,11,Île-de-France,91,Essonne,48.736,2.291,91300,Oui,high,Antony,admin:fr:91377

In [5]:
# travel_list=[]
# for i in df2["id_region"]:
#     for j in df2["id_region"]:
#         if i!=j:
#             start=df2[df2["id_region"]==i]["Nom_Gare"].tolist()[0]
#             arrival=df2[df2["id_region"]==j]["Nom_Gare"].tolist()[0]
#             id_start=i
#             id_arrival=j
#             travel_list.append([start,arrival,id_start,id_arrival])
# df3=pd.DataFrame(travel_list,columns=['start','arrival','id_start','id_arrival'])

import random
randomlist = []
for i in range(0,3):
    n = random.randint(1,len(df2))
    randomlist.append(n)
    
travel_list=[]
for i in df2["id_region"]:
    randomlist = []
    for k in range(0,3):
        n = random.randint(1,len(df2)-1)
        randomlist.append(n)
    for j in randomlist:
        if i!=df2.iloc[j]["id_region"]:
            start=df2[df2["id_region"]==i]["Nom_Gare"].tolist()[0]
            arrival=df2.iloc[j]["Nom_Gare"]
            id_start=i
            id_arrival=df2.iloc[j]["id_region"]
            travel_list.append([start,arrival,id_start,id_arrival])
df3=pd.DataFrame(travel_list,columns=['start','arrival','id_start','id_arrival'])

In [6]:
df3

                         start     arrival        id_start      id_arrival
0          Aix-en-Provence TGV   Perpignan  admin:fr:13001  admin:fr:66136
1          Aix-en-Provence TGV      Frasne  admin:fr:13001  admin:fr:25259
2          Aix-en-Provence TGV       Arras  admin:fr:13001  admin:fr:62041
3              Bourg-en-Bresse  Le Croisic  admin:fr:01053  admin:fr:44049
4              Bourg-en-Bresse     Bayonne  admin:fr:01053  admin:fr:64102
..                         ...         ...             ...             ...
386  Belfort - Montbéliard TGV    La Teste  admin:fr:90068  admin:fr:33529
387  Belfort - Montbéliard TGV        Sète  admin:fr:90068  admin:fr:34301
388                  Massy TGV    Narbonne  admin:fr:91377  admin:fr:11262
389                  Massy TGV    Poitiers  admin:fr:91377  admin:fr:86194
390                  Massy TGV    Biarritz  admin:fr:91377  admin:fr:64122

[391 rows x 4 columns]

In [7]:
from datetime import datetime,timedelta
def convertir_en_chaine(dt) :
    ''' on convertit en chaîne de caractères un datetime'''
    return datetime.strftime(dt, '%Y%m%dT%H%M%S')

now = datetime.now()
convertir_en_chaine(now)

'20220321T175635'

In [8]:
def convertir_en_temps(chaine) :
    ''' on convertit en date la chaine de caractères de l API'''
    return datetime.strptime(chaine.replace('T',''),'%Y%m%d%H%M%S')

convertir_en_temps(convertir_en_chaine(now))

datetime.datetime(2022, 3, 21, 17, 56, 35)

In [16]:
exist=[]
arrival_date=[]
start_date=[]

for i in range(len(df3)):
    gare_depart=df3["id_start"].loc[i]    
    gare_arrivee=df3["id_arrival"].loc[i]
    query = requests.get(
        ('https://api.sncf.com/v1/coverage/sncf/journeys?'
         'from={}&to={}&datetime={}').format(gare_depart, gare_arrivee,'20220322T120000'),
        auth=("5b3cc55f-1fec-4bd9-8e09-957b4de0c84b", '')).json()
    if("journeys" in query.keys()):
        start_date.append(convertir_en_temps('20220322T120000'))
        arrival_date.append(convertir_en_temps(query['journeys'][0]['arrival_date_time']))
        exist.append(True)
        
    else:
        start_date.append(convertir_en_temps('20220322T120000'))
        arrival_date.append(convertir_en_temps('20220322T120000'))
        exist.append(False)
    if(i%100==0):
        print(i)
        
df3['exist']=exist
df3['arrival_date']=arrival_date
df3['start_date']=start_date

0
100
200
300

In [17]:
df3

,start,arrival,id_start,id_arrival,exist,arrival_date,start_date
0,Aix-en-Provence TGV,Perpignan,admin:fr:13001,admin:fr:66136,True,2022-03-22 16:12:00,2022-03-22 12:00:00
1,Aix-en-Provence TGV,Frasne,admin:fr:13001,admin:fr:25259,True,2022-03-22 19:17:00,2022-03-22 12:00:00
2,Aix-en-Provence TGV,Arras,admin:fr:13001,admin:fr:62041,True,2022-03-22 17:40:30,2022-03-22 12:00:00
3,Bourg-en-Bresse,Le Croisic,admin:fr:01053,admin:fr:44049,True,2022-03-22 18:19:00,2022-03-22 12:00:00
4,Bourg-en-Bresse,Bayonne,admin:fr:01053,admin:fr:64102,True,2022-03-22 20:03:00,2022-03-22 12:00:00
...,...,...,...,...,...,...,...
386,Belfort - Montbéliard TGV,La Teste,admin:fr:90068,admin:fr:33529,True,2022-03-22 20:23:00,2022-03-22 12:00:00
387,Belfort - Montbéliard TGV,Sète,admin:fr:90068,admin:fr:34301,True,2022-03-22 19:47:00,2022-03-22 12:00:00
388,Massy TGV,Narbonne,admin:fr:91377,admin:fr:11262,True,2022-03-22 18:59:00,2022-03-22 12:00:00
389,Massy TGV,Poitiers,admin:fr:91377,admin:fr:86194,True,2022-03-22 14:44:00,2022-03-22 12:00:00
390,Massy TGV,Biarritz,admin:fr:91377,admin:fr:64122,True,2022-03-22 18:37:00,2022-03-22 12:00:00

In [18]:
df3['exist'].unique()

array([ True, False])

In [19]:
df3.to_json(r'Data/travel.json',orient="records")

In [20]:
df4=df3.copy()

In [24]:
df4["travel_time"]=df3["arrival_date"]-df3["start_date"]

In [25]:
df4.to_json(r'Data/travel.json',orient="records")

,start,arrival,id_start,id_arrival,exist,arrival_date,start_date,travel_time
0,Aix-en-Provence TGV,Perpignan,admin:fr:13001,admin:fr:66136,True,2022-03-22 16:12:00,2022-03-22 12:00:00,0 days 04:12:00
1,Aix-en-Provence TGV,Frasne,admin:fr:13001,admin:fr:25259,True,2022-03-22 19:17:00,2022-03-22 12:00:00,0 days 07:17:00
2,Aix-en-Provence TGV,Arras,admin:fr:13001,admin:fr:62041,True,2022-03-22 17:40:30,2022-03-22 12:00:00,0 days 05:40:30
3,Bourg-en-Bresse,Le Croisic,admin:fr:01053,admin:fr:44049,True,2022-03-22 18:19:00,2022-03-22 12:00:00,0 days 06:19:00
4,Bourg-en-Bresse,Bayonne,admin:fr:01053,admin:fr:64102,True,2022-03-22 20:03:00,2022-03-22 12:00:00,0 days 08:03:00
...,...,...,...,...,...,...,...,...
386,Belfort - Montbéliard TGV,La Teste,admin:fr:90068,admin:fr:33529,True,2022-03-22 20:23:00,2022-03-22 12:00:00,0 days 08:23:00
387,Belfort - Montbéliard TGV,Sète,admin:fr:90068,admin:fr:34301,True,2022-03-22 19:47:00,2022-03-22 12:00:00,0 days 07:47:00
388,Massy TGV,Narbonne,admin:fr:91377,admin:fr:11262,True,2022-03-22 18:59:00,2022-03-22 12:00:00,0 days 06:59:00
389,Massy TGV,Poitiers,admin:fr:91377,admin:fr:86194,True,2022-03-22 14:44:00,2022-03-22 12:00:00,0 days 02:44:00
390,Massy TGV,Biarritz,admin:fr:91377,admin:fr:64122,True,2022-03-22 18:37:00,2022-03-22 12:00:00,0 days 06:37:00